---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

## 12.2

-   Grace's Note: Accidentally created my own repo, but teammates helped me use team link instead.

-   Logan: Created the repo and had no issues. Found URL with no problem

-   Lexi's Note:

-   Nate's Note: Had to install Git onto my computer first but otherwise was able to access the repo and copy the URL.

## 12.3

-   Grace's note: Had no issue creating new project

-   Logan:Had a little trouble finding where to insert the GIT URL when I made the new project, but after talking with team I was able to make it.

-   Lexi's Note:

-   Nate's Note: Was able to create new project without any issues arising

## 12.4

-   Grace's Note: Was able to see "This is from RStudio"

-   Logan: Modified the file with no problem. Am able to add all my changes!

-   Lexi's Note:

-   Nate's Note: Successfully edited `README` file, was able to save and commit

## 12.5

-   Grace's Note: Teammates helped me find push button

-   Logan:When commiting I had issues with credentials and had to enter in my info to the terminal. After I did that I was able to succesfully commit and push my work.

-   Lexi's Note:

-   Nate's Note: Committed `README` file successfully pushed without error

## 12.6

-   Grace's Note: Can see the changes in the group repo

-   Logan: Was able to see the changes!

-   Lexi's Note:

-   Nate's Note: Committed changes visible upon returning to Github

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.
